image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: Setup Lein and build template
    init: |
      # Java 17 and lein are preinstalled in the image
      java -version
      lein -v
      lein clean && lein deps && lein install
    command: |
      echo "Java in Setup task:" && java -version && which java
      if [ ! -d myapp ]; then
        # Generate a default Leiningen app project
        lein new app myapp
      fi
      cd myapp
      echo "Run 'lein run' to start the app."
      echo "This workspace now uses a default Leiningen app (not the lst template)."
  - name: Run dev server
    command: |
  echo "Java in Dev Server task:" && java -version && which java
  # Wait for the project to be created by the setup task
  until [ -f myapp/project.clj ]; do
        echo "Waiting for gpapp to be ready..."
        sleep 2
      done
  cd myapp
  lein run
