image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: Setup Lein and build template
    init: |
      # Java 17 and lein are preinstalled in the image
      java -version
      lein -v
      lein clean && lein deps && lein install
    command: |
      if [ ! -d myapp ]; then
        # Generate an LST web app from this template
        lein new lst myapp
      fi
      cd myapp
      echo "Run 'lein with-profile dev run' to start the LST app on port 3000."
      echo "This workspace now uses the LST template."
      # Create a workspace file and open it to switch editor context to myapp
      cat > myapp.code-workspace <<'EOF'
      {
        "folders": [ { "path": "." } ],
        "settings": {}
      }
      EOF
  gp open myapp.code-workspace || true
  - name: Run dev server
    command: |
      # Wait for the project to be created by the setup task
      until [ -f myapp/project.clj ]; do
        echo "Waiting for myapp to be ready..."
        sleep 2
      done
      cd myapp
  lein with-profile dev run
