name: Create demo GIF

on:
  workflow_dispatch:
    inputs:
      fps:
        description: Frames per second (lower = slower)
        required: false
        default: '3'
  push:
    branches:
      - main
    paths:
      - 'screenshot-*.png'

permissions:
  contents: write

jobs:
  build-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - id: prep
        name: Prepare frames
        run: |
          mkdir -p docs
          # If you want a curated order, list them explicitly; otherwise glob all
          if ls screenshot-*.png >/dev/null 2>&1; then
            ls -1 screenshot-*.png > frames.txt
          else
            echo "skip=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

      - name: Build GIF
        if: steps.prep.outputs.skip != 'true'
        run: |
          FPS_INPUT='${{ github.event.inputs.fps }}'
          if [ -z "$FPS_INPUT" ]; then FPS=3; else FPS="$FPS_INPUT"; fi
          if ! echo "$FPS" | grep -Eq '^[0-9]+$'; then FPS=3; fi
          if [ "$FPS" -le 0 ]; then FPS=3; fi
          DELAY=$(( 100 / FPS ))
          convert \
            -dispose previous \
            -delay "$DELAY" \
            -loop 0 \
            -resize 1200x \
            @frames.txt \
            -layers Optimize docs/demo.gif

      - name: Commit GIF
        if: hashFiles('docs/demo.gif') != ''
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/demo.gif
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(docs): add/update demo.gif (auto-generated)"
          git push
